services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: ppurisam_frontend
    networks:
      - ppurisam_network
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # React 파일 감시 설정

networks:
  ppurisam_network:
    driver: bridge