services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: ppurisam_frontend
    networks:
      - ppurisam_network
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # 파일 변경 감지
    command: ["npm", "run", "dev"] # npm start 대신 Vite 서버 실행

networks:
  ppurisam_network:
    driver: bridge
